# Site metadata.

# Canonical URL
url: https://pulse.cio.gov

name: Pulse
title: "The pulse of the federal .gov space"
description: "How federal government domains are meeting best practices on the web."

# When the data we used was generated. Manually updated for now.
data:
  # The export date for the .gov domain list.
  domains: 2015-03-15
  # The export date for the DAP participating sub/domain list.
  dap: 2015-05-29
  # The scan date for HTTP/TLS data.
  scan: 2015-06-26

# Markdown configuration.
highlighter: rouge
markdown: redcarpet
redcarpet:
  syntax_highlighter: rouge
  extensions:
  - smart
  - with_toc_data

# Jekyll compilation.
exclude:
- ".ruby-version"
- ".python-version"
- ".jekyll-metadata"
- ".sass-cache"
- ".gitignore"
- ".travis.yml"
- "manifest.yml"
- todo.txt
- Gemfile
- Gemfile.lock
- deploy
- data
- Staticfile
- Makefile
- vendor
- lib
- README.md
- CONTRIBUTING.md
- LICENSE.md
